### PR TITLE
Support Locationiq API

### PR DESCRIPTION
**Pull request by Daredzik**
+ Locationiq API (its based od nominatim api but need to provide key and some endpoint have different url) https://locationiq.com/docs

### CODE REVIEW

**Comment by Daredzik** [comment]
@perliedman what do you think about it ??

**Comment by Daredzik** [comment]
@perliedman 
yes its a nice suggestion, but it's not that easy. Coz `Locationiq` endpoints are not equals to `Nominatim`, example:
`Nominatim` version : `reverse`
`Locationiq` version: `reverse.php`

How you want to change this using extend without modified `Nominatim` class ?

**Comment by perliedman** [comment]
Hm, yes I see. I think it could be reasonable to modify the `Nominatim` class so that the endpoint names are options, that you can then override in `Locationiq`. It's not entirely unreasonable that this change could also be useful in other scenarios.

**Comment by simon04** [comment]
Feel free to reopen once you address the requested changes.

**Pull request closed without merging**
