### PR TITLE
[fix] trigger on ontouchstart event for android

### PR DESCRIPTION
**Pull request by loispostula**
As seen in https://github.com/perliedman/leaflet-control-geocoder/issues/170 clicking on search result wasn't doing anythin.

This fixes that

### CODE REVIEW

**Comment by perliedman** [comment]
Looks good, thanks! 👍

**Comment by loispostula** [comment]
Any chance for a release soon?

**Comment by perliedman** [comment]
I'll try to squeeze it in in the coming days, but can't promise anything, sorry!

**Comment by loispostula** [comment]
up?

**Comment by perliedman** [comment]
Newly released 1.5.8 contains this fix!

**Pull request merged**
