### PR TITLE
Bugfix: fix default geocoder option

### PR DESCRIPTION
**Pull request by n4nn31355**

### CODE REVIEW

**Comment by perliedman** [comment]
Hi, thanks!

Does this fix an issue you're experiencing? The `Nominatim` variable is declared in this module already, so it should work as it is.

A plan in the long term is to decouple as much of the code as possible from the `L.Control.Geocoder` namespace, so I'm reluctant to merge this unless there's a real problem with the code as it is now.

**Comment by perliedman** [comment]
I see now that there's a problem. I will check why it's not working as intended.

**Comment by n4nn31355** [comment]
Thanks!
I'm not so familiar with js and this bug may have another solution, but it workaround works for me.

**Comment by perliedman** [comment]
I've fixed this and released a new version, 1.3.1.

Thanks for notifying me of the bug!

**Pull request closed without merging**
