### PR TITLE
Patch for ie script1028

### PR DESCRIPTION
**Pull request by SilentT-FR**
Fix https://github.com/perliedman/leaflet-control-geocoder/issues/102

### CODE REVIEW

**Comment by perliedman** [comment]
Thanks for this!

I had a look at this, and while I certainly appreciate the work you put in here, the style IE8 forces on you just looks horrible. Not to mention that it's brittle and easy to make the same mistake again.

Instead, I found a Browserify transform called [`es3ify`](https://github.com/spicyj/es3ify), that performs these fixes automatically when building the dist. I've applied it in b61b92788ecaaec52cc88634a9073a034ca33b37, and released version 1.3.2 that should hopefully work with IE8.

Thanks again for bringing this problem to my attention, and also many thanks for putting in the time to improve the plugin, all help is awesome and really appreciated.

**Comment by SilentT-FR** [comment]
BUt https://github.com/SilentT-FR/leaflet-control-geocoder/commit/fb06c876c9ab064d654ea78f28cd37b0f1f863e9

The Line 17 have ,}, and other files and lines contains this errors ... Es3ify repair this ? 



Envoyé de mon iPhone

**Comment by perliedman** [comment]
Yes, es3ify removes trailing commas as well. Having said that, I don't have IE8 available to test, so if you still experience issues, keep me posted!

**Comment by SilentT-FR** [comment]
i use the builded here : http://www.liedman.net/leaflet-control-geocoder/download/

and its work :) :+1: 

es3ify repair this lines https://github.com/spicyj/es3ify/blob/master/index.js#L68 you have wright

IE 7 & IE 8 tested and its ok

**Comment by perliedman** [comment]
Perfect! Thanks.

**Pull request closed without merging**
