### PR TITLE
Add search by LatLon coordinates

### PR DESCRIPTION
**Pull request by Gia90**
It allows to search for locations by Lat Lon coordinates (accepted format: "x.xxxxx y.yyyyy" or "x.xxxxx, y.yyyyy")

### CODE REVIEW

**Comment by mpbotti** [comment]
Customizing 2
I would like to leave the standard marker at its location for 2" (or so) and then vanishing it leaving a clear map. How can I do that? Thnx, M.

**Comment by perliedman** [comment]
@mpbotti this is definitely not the right place to ask that question, but have a look at the section on [customizing](https://github.com/perliedman/leaflet-control-geocoder#customizing), you can add an event handler and use a `setTimeout` or similar technique.

**Comment by mpbotti** [comment]
Thanks @perliedman for your feedback, and my apoligies for my question... Regards, M.

**Comment by perliedman** [comment]
Closing this since it's way too old to do anything with.

_If_ you want this type of functionality, it's better off as its own geocoder instance (a geocoder is something that given string input gives you a location - parsing a lat/lng coordinate is one special form of geocoder).

**Pull request closed without merging**
