### PR TITLE
WIP: Migrate to TypeScript

### PR DESCRIPTION
**Pull request by simon04**

### CODE REVIEW

**Comment by perliedman** [comment]
Hi @simon04, I had totally missed this change!

I still don't do TypeScript myself, but if this is something you'd prefer, I say go for it!

Also, vaguely related: these days you seem to do almost all of the work on this project, and I feel sort of bad about the repo being in my name. I'd be happy to hand over the repo to you if you prefer, or if we can come up with some other solution to give you more credit for your work!

**Comment by simon04** [comment]
Concerning the attribution, I might add a Authors section to README.md. Besides that, Git records the history good enough. :smile: 

If we wanted to move the project, I'd suggest an independent namespace. Could it be moved to https://github.com/leaflet/ (considering that many plugins are already there)?

**Comment by grabeqx** [comment]
Hi @simon04 @perliedman Do you have some plans to merge this pr soon?

**Comment by descl** [comment]
Hey, will this PR be merged soon? we would love to use it 👼

**Pull request merged**
