### PR TITLE
Inherit from 'L.Evented' instead of deprecated 'L.Mixin.Events'

### PR DESCRIPTION
**Pull request by sedenardi**
Fixes the issue mentioned in https://github.com/perliedman/leaflet-control-geocoder/issues/168. No new tests are required.

### CODE REVIEW

**Comment by perliedman** [comment]
Thanks!

**Comment by sedenardi** [comment]
No problem @perliedman. Let me know if/when you push a new version to NPM. Thanks for your work on this module.

**Comment by zakjan** [comment]
Hi @perliedman, could you release this to npm?

**Comment by sedenardi** [comment]
Hey @perliedman, any update on this?

**Comment by perliedman** [comment]
Hi guys, this fix is included in the release 1.5.6 a while ago!

**Comment by sedenardi** [comment]
@perliedman Awesome, thank you so much for all your hard work. It's much appreciated!

**Pull request merged**
